added `husky` pre-commit hook to the Repo
ActionsDesk/cascading-downstream-merge pull request #6
Opened 2022-06-06 14:02 UTC by jefeish

This feature will create a new `dist/index.js` every time a commit is made. The intention is to keep the `src/index.js` and the *compiled* `dist/index.js` in sync with every commit.

2022-06-06 14:51 UTC, jdesulme commented
@jefeish Seems like your PR is failing on a new lint for the BASH script

2022-06-07 20:47 UTC, bakosa requested changes

2022-06-07 20:48 UTC, bakosa commented on .husky/pre-commit
> +git add dist/index.js dist/LICENSE
Would be possible to add linting here too to work with the super linter?

2022-06-13 20:57 UTC, bakosa approved these changes

2022-06-13 20:57 UTC, jdesulme approved these changes

2022-06-13 21:13 UTC, merged